import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import useAuth from 'utils/useAuth';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const auth = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {auth.email || <button onClick={auth.signIn}>login</button>}
      <br />
      <Link href="/other">
        <a>to other page</a>
      </Link>

      <div>
        <Link href="/profile/username/store">
          <a>profile store</a>
        </Link>
        <br />
        <Link href="/upload_complete_work">
          <a>upload complete work</a>
        </Link>
        <Link href="/product_post_popup">
          <a>Product post popup</a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
