import tw, { css } from 'twin.macro';
import Link from 'next/link';
import Head from 'next/head';
import internal from 'stream';
import { Dispatch, SetStateAction } from 'react';

const inactiveButton = css`
  ${tw`opacity-25 cursor-default`}
`;
const activeButton = css`
  ${tw`opacity-75 cursor-pointer`}
`;

const activeTab = css`
  ${tw`bg-theme-red`}
`;
const inactiveTab = css`
  ${tw`bg-gray-300`}
`;

const NUM_STAGES = 2;

function CompleteWorkTabSelector(props: {
  stage: number;
  setStage: Dispatch<SetStateAction<number>>;
}) {
  return (
    <>
      <Head>
        <title>Pkazo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.11.1/css/all.css"
        ></link>
      </Head>

      <div tw="flex mt-16 items-center justify-between gap-10 px-[40px] max-w-[1250px] my-6 mx-auto">
        <div
          css={[
            tw`flex items-center gap-1`,
            props.stage === 0 ? inactiveButton : activeButton,
          ]}
          onClick={
            props.stage === 0
              ? undefined
              : () => props.setStage((state: number) => Math.max(0, state - 1))
          }
        >
          <i className="far fa-angle-left text-2xl"></i>
          <span>Back</span>
        </div>

        <div
          css={[
            tw`flex items-center gap-1`,
            props.stage === NUM_STAGES ? inactiveButton : activeButton,
          ]}
          onClick={
            props.stage === NUM_STAGES
              ? undefined
              : () =>
                  props.setStage((state: number) =>
                    Math.min(NUM_STAGES, state + 1)
                  )
          }
        >
          <span>Skip</span>
          <i className="far fa-angle-right text-2xl"></i>
        </div>
      </div>

      <div tw="grid grid-cols-3  px-[40px] max-w-[1000px]  my-6 mx-auto ">
        <div
          css={[tw`h-[3px]`, (props.stage === 0 && activeTab) || inactiveTab]}
        ></div>
        <div
          css={[tw`h-[3px]`, (props.stage === 1 && activeTab) || inactiveTab]}
        ></div>
        <div
          css={[tw`h-[3px]`, (props.stage === 2 && activeTab) || inactiveTab]}
        ></div>
      </div>

      <div tw="grid grid-cols-3  px-[40px] max-w-[1000px] my-6 mx-auto">
        <div
          css={[
            tw`flex items-center justify-center leading-[0.4] opacity-90`,
            props.stage === 0 ? undefined : tw`cursor-pointer`,
          ]}
          onClick={props.stage === 0 ? undefined : () => props.setStage(0)}
        >
          Work Information
        </div>
        <div
          css={[
            tw`flex items-center justify-center leading-[0.4] opacity-90`,
            props.stage === 1 ? undefined : tw`cursor-pointer`,
          ]}
          onClick={props.stage === 1 ? undefined : () => props.setStage(1)}
        >
          In Progress Posts
        </div>
        <div
          css={[
            tw`flex items-center justify-center leading-[0.4] opacity-90`,
            props.stage === 2 ? undefined : tw`cursor-pointer`,
          ]}
          onClick={props.stage === 2 ? undefined : () => props.setStage(2)}
        >
          Include In Portfolios
        </div>
      </div>
    </>
  );
}

export default CompleteWorkTabSelector;
